version: '2'
services:
  elastic:
    image: elasticsearch
  flashlight:
    image: netresearch/flashlight
    links:
      - elastic
    environment:
      ES_HOST: "elastic"
    volumes:
      - ./flashlight.js:/opt/app/config.js
      - ./src/models/Config.js:/opt/app/src/models/Config.js
      - ./.firebaserc:/opt/app/.firebaserc